<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>zb</string>
	</array>
	<key>name</key>
	<string>Zoidberg</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(extern)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.extern</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Extern declaration</string>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>meta.declaration.extern</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.declaration</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Actual</string>
					<key>match</key>
					<string>\G\s+(\w+)\s*(?::\s*([\w&lt;&gt;\[\]]+)\s*)?</string>
					<key>name</key>
					<string>meta.declaration.extern.body</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(interfa2ce)\s+(\w+)\s*\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.interface</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Interface declaration</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.declaration.interface</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.declaration</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Interface field</string>
					<key>match</key>
					<string>(\w+)\s*:\s*([\w&lt;&gt;\[\]]+);</string>
					<key>name</key>
					<string>meta.declaration.interface.field</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\w+)\s*\(</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Function declaration</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.declaration.function</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Parameter</string>
					<key>match</key>
					<string>(\w+)\s*:\s*([\w&lt;&gt;\[\]]+)</string>
					<key>name</key>
					<string>meta.declaration.function.parameter</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>comment</key>
			<string>Function body</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.declaration.function.body</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.declaration</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Value binding</string>
					<key>match</key>
					<string>(\w+)\s*:\s*([\w&lt;&gt;\[\]]+\s*)(?:=\s*[^;]+\s*);</string>
					<key>name</key>
					<string>meta.declaration.value</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.zoidberg</string>
	<key>uuid</key>
	<string>cd4ca271-0767-44ea-b884-d2d36705ba51</string>
</dict>
</plist>
